lambda-error-sns-sender/__init__.py,sha256=57maqgLN16vtj9srBRxSHZXMJSDburMURFbOSq0xy74,25041
lambda-error-sns-sender/py.typed,sha256=AbpHGcgLb-kRsJGnwFEktk7uzpZOCcBY74-YBdrKVGs,1
lambda-error-sns-sender/_jsii/__init__.py,sha256=p7W5z_V6YGxoFyIdEpwy0iYmeYrIi3Iaa6JxF8uqX18,428
lambda-error-sns-sender/_jsii/lambda-error-sns-sender@0.0.49.jsii.tgz,sha256=LffxxHC6-9GpDmrX_jCZJSlxdZAewX6QgUkxI-05PQs,34046
lambda_error_sns_sender-0.0.49.dist-info/LICENSE,sha256=z8d0m5b2O9McPEK1xHG_dWgUBT6EfBDz6wA0F7xSPTA,11358
lambda_error_sns_sender-0.0.49.dist-info/METADATA,sha256=yymxeu9JLycr_ozSB07t3TWLGrgZsrClhzq02zPoqRo,2102
lambda_error_sns_sender-0.0.49.dist-info/WHEEL,sha256=5sUXSg9e4bi7lTLOHcm6QEYwO5TIF1TNbTSVFVjcJcc,92
lambda_error_sns_sender-0.0.49.dist-info/top_level.txt,sha256=FkMA9jPLJsN588vpcg5IZxGjGTXyTWVbDBZNa2cu0yI,24
lambda_error_sns_sender-0.0.49.dist-info/RECORD,,
